{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  labels:
    app.kubernetes.io/name: {{ include "brsp.name" . }}
    helm.sh/chart: {{ include "brsp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if (.Values.letsencrypt).enabled }}
    cert-manager.io/issuer: {{ include "letsencrypt.issuerName" . }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.ingress.hosts }}
  rules:
    {{ range . }}
    {{- $host := . -}}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range $host.paths }}
          - backend:
              service:
                name: {{ .app }}-{{ $host.environment }}
                port:
                  {{- if $host.portName }}
                  name: {{ $host.portName }}
                  {{- end }}
                  {{- if $host.portNumber }}
                  number: {{ $host.portNumber }}
                  {{- end }}
            path: {{ .path }}
            pathType: {{ .pathType }}
          {{- end }}
    {{ end }}
  {{- end }}
  {{ if (.Values.ingress).tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{ end }}
{{ end }}
