---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brsp-ingress
  namespace: brsp
spec:
  rules:
    # - host: "bridgespero.com"
    #   http:
    #     paths:
    #       - path: /
    #         pathType: Prefix
    #         backend:
    #           service:
    #             name: next-svc
    #             port:
    #               number: 3000
    - host: "dev.bridgespero.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: next-dev-svc
                port:
                  number: 3000
