apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-dev
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: next
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: dev
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: frontend
spec:
  {{- $nextReplicas := .Values.next.replicas -}}
  {{- if kindIs "float64" $nextReplicas }}
  replicas: {{ $nextReplicas }}
  {{- else }}
  replicas: {{ $nextReplicas.dev | default "1" }}
  {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "brsp.name" . }}
      app.kubernetes.io/component: next
      environment: dev
      release: {{ .Release.Name }}
      tier: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "brsp.name" . }}
        app.kubernetes.io/component: next
        environment: dev
        release: {{ .Release.Name }}
        tier: frontend
    spec:
      containers:
        - name: next-dev
          image: "{{ .Values.next.image.repository }}:{{ .Values.next.image.tag.dev }}"
          imagePullPolicy: {{ .Values.next.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.next.containerPort }}
              protocol: TCP
          env:
            - name: BRSP_ENV
              value: dev
          {{- with .Values.configMaps.next }}
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: apiUrl.dev
            - name: NEXT_PUBLIC_PAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: pageUrl.dev
          {{- end }}
          resources:
{{- with .Values.next }}
{{ toYaml .resources | indent 12 }}
  {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.cr }}
