apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-dev
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/environment: dev
    app.kubernetes.io/component: frontend
    helm.sh/chart: {{ template "brsp.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.next.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: next
      app.kubernetes.io/environment: dev
      app.kubernetes.io/component: frontend
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: next
        app.kubernetes.io/environment: dev
        app.kubernetes.io/component: frontend
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: next-dev
          image: "{{ .Values.next.image.repository }}:{{ .Values.next.image.tag.dev }}"
          imagePullPolicy: {{ .Values.next.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.next.containerPort }}
              protocol: TCP
          resources:
  {{- with .Values.next }}
{{ toYaml .resources | indent 12 }}
    {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
  {{- end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.cr }}
