{{ if has "dev" .Values.environment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dev
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: spring
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: dev
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
spec:
  {{- $springReplicas := .Values.spring.replicas -}}
  {{- if kindIs "float64" $springReplicas }}
  replicas: {{ $springReplicas }}
  {{- else }}
  replicas: {{ $springReplicas.dev | default "1" }}
  {{- end }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "brsp.name" . }}
      app.kubernetes.io/component: spring
      environment: dev
      release: {{ .Release.Name }}
      tier: backend
  minReadySeconds: {{ (.Values.spring).minReadySeconds | default "10" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "brsp.name" . }}
        app.kubernetes.io/component: spring
        environment: dev
        release: {{ .Release.Name }}
        tier: backend
    spec:
      terminationGracePeriodSeconds: {{ (.Values.spring).terminationGracePeriodSeconds | default "10" }}
      initContainers:
        - name: wait-for-services
          image: busybox
          imagePullPolicy: {{ ((.Values.spring).image).pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh","-c"]
          args:
            - |-
              [[ -n "$STATIC_DIR" ]] && { mkdir -pv "$STATIC_DIR"; chown -R 111:111 "$STATIC_DIR"; }
              [[ -n "$PRIV_DIR" ]] && { mkdir -pv "$PRIV_DIR"; chown -R 111:111 "$PRIV_DIR"; }
              until
                echo 'Waiting for postgres...' &&
                nc -vz -w 2 {{ template "postgres.service.name" . }}-$BRSP_ENV-rw{{ template "brsp.service.uriSuffix" . }} 5432 &&
                echo 'Waiting for redis...' &&
                nc -vz -w 2 {{ template "redis.service.name" . }}-$BRSP_ENV{{ template "brsp.service.uriSuffix" . }} 6379
              do
                echo 'Looping forever...'
                sleep 2
              done
          securityContext:
            readOnlyRootFilesystem: true
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.spring }}
          env:
            - name: BRSP_ENV
              value: dev
          volumeMounts:
            - name: data
              mountPath: {{ (.Values.spring).dataPath | default "/usr/share/spring" }}
      containers:
        - name: spring-dev
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag.dev }}"
          imagePullPolicy: {{ ((.Values.spring).image).pullPolicy | default "IfNotPresent" }}

          startupProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.spring.containerPort }}
            failureThreshold: 30
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.spring.containerPort }}
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: {{ .Values.spring.containerPort }}
            periodSeconds: 10

          ports:
            - containerPort: {{ .Values.spring.containerPort }}
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.configMaps.spring }}
            - secretRef:
                name: {{ .Values.secrets.spring }}
          env:
            - name: BRSP_ENV
              value: dev
            - name: BRSP_URL
              value: {{ index .Values.next.env "bluegreen.NEXT_PUBLIC_PAGE_URL" }}
          volumeMounts:
            - name: data
              mountPath: {{ (.Values.spring).dataPath | default "/usr/share/spring" }}
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          resources:
{{- with .Values.spring }}
{{ toYaml .resources | indent 12 }}
  {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.cr }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spring-dev
        - name: empty-dir
          emptyDir: {}
{{ end }}
