apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-dev
  labels:
    app.kubernetes.io/name: {{ template "brsp.name" . }}
    app.kubernetes.io/component: spring
    helm.sh/chart: {{ template "brsp.chart" . }}
    environment: dev
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    tier: backend
spec:
  {{- $springReplicas := .Values.spring.replicas -}}
  {{- if kindIs "float64" $springReplicas }}
  replicas: {{ $springReplicas }}
  {{- else }}
  replicas: {{ $springReplicas.dev | default "1" }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "brsp.name" . }}
      app.kubernetes.io/component: spring
      environment: dev
      release: {{ .Release.Name }}
      tier: backend
  minReadySeconds: {{ (.Values.spring).minReadySeconds | default "10" }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "brsp.name" . }}
        app.kubernetes.io/component: spring
        environment: dev
        release: {{ .Release.Name }}
        tier: backend
    spec:
      terminationGracePeriodSeconds: {{ (.Values.spring).terminationGracePeriodSeconds | default "10" }}
      initContainers:
        - name: wait-for-services
          image: busybox
          imagePullPolicy: {{ ((.Values.spring).image).pullPolicy | default "IfNotPresent" }}
          command: ["/bin/sh","-c"]
          args:
            - |-
              [[ -n "$STATIC_DIR" ]] && { mkdir -pv "$STATIC_DIR"; chown -R 111:111 "$STATIC_DIR"; }
              [[ -n "$PRIV_DIR" ]] && { mkdir -pv "$PRIV_DIR"; chown -R 111:111 "$PRIV_DIR"; }
              until
                echo 'Waiting for postgres...' &&
                nc -vz -w 2 {{ template "postgres.service.name" . }}-$BRSP_ENV-rw{{ template "brsp.service.uriSuffix" . }} 5432 &&
                echo 'Waiting for redis...' &&
                nc -vz -w 2 {{ template "redis.service.name" . }}-$BRSP_ENV{{ template "brsp.service.uriSuffix" . }} 6379
              do
                echo 'Looping forever...'
                sleep 2
              done
          securityContext:
            readOnlyRootFilesystem: true
          env:
            - name: BRSP_ENV
              value: bluegreen
          {{- with .Values.configMaps.spring }}
            - name: STATIC_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: staticDir
                  optional: true
            - name: PRIV_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: privDir
                  optional: true
          {{- end }}
      containers:
        - name: spring-dev
          image: "{{ .Values.spring.image.repository }}:{{ .Values.spring.image.tag.dev }}"
          imagePullPolicy: {{ ((.Values.spring).image).pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.spring.containerPort }}
              name: http
              protocol: TCP
          env:
            - name: BRSP_ENV
              value: dev
            - name: BRSP_URL
              value: {{ .Values.url.dev }}
          {{- with .Values.configMaps.spring }}
            - name: DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: datasourceUsername
            - name: DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: datasourceUrl
            - name: REPLICA_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: replicaDatasourceUrl
            - name: REDIS_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: redisAddress
            - name: ZOOM_REDIRECT_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: zoomRedirectUri
            - name: STATIC_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: staticDir
                  optional: true
            - name: PRIV_DIR
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: privDir
                  optional: true
            - name: JPA_SHOWSQL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: jpaShowSql
                  optional: true
            - name: JPA_FORMATSQL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: jpaFormatSql
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: logLevel
                  optional: true
            - name: SPRING_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: springPort
                  optional: true
            - name: IS_DROP_FIRST
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: isDropFirst
                  optional: true
            - name: DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: {{ . }}
                  key: ddlAuto
                  optional: true
          {{- end }}
          {{- with .Values.secrets.spring }}
            - name: DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: datasourcePassword
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: jwtSecret
            - name: SUPER_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: superAdminEmail
            - name: SUPER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: superAdminPassword
            - name: ZOOM_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: zoomClientId
            - name: ZOOM_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: zoomClientSecret
            - name: ZOOM_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ . }}
                  key: zoomWebhookSecret
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ (.Values.spring).dataPath | default "/usr/share/spring" }}
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
          resources:
{{- with .Values.spring }}
{{ toYaml .resources | indent 12 }}
  {{- with .nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .affinity }}
      affinity:
{{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
  {{- end }}
{{- end }}
      imagePullSecrets:
        - name: {{ .Values.secrets.cr }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spring-dev
        - name: empty-dir
          emptyDir: {}
